only_pets/main/routes.py
"""Import packages and modules."""
from os import abort
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from datetime import date, datetime

import flask_login
from only_pets.models import *
from only_pets.main.forms import *

# Import app and db from events_app package so that we can run app
from only_pets.extensions import app, db, bcrypt

main = Blueprint("main", __name__)

##########################################
#           Home Route                  #
##########################################


@main.route('/')
def homepage():
    all_posts = Post.query.all()
    all_users = User.query.all()
    all_stories = Story.query.all()
    return render_template('home.html',
     all_users=all_users, all_posts=all_posts, all_stories=all_stories)

@main.route('/profile/<username>')
def profile(username):
    user = User.query.filter_by(username=username).one()
    posts = Post.query.filter(Post.created_by.has(username = username))
    return render_template('profile.html', user=user, posts=posts)


##########################################
#           User Routes                 #
##########################################
@main.route('/create_user', methods=['GET', 'POST'])
@login_required
def create_user():
    form = UserForm()
    #validate form
    if form.is_submitted():
        new_user = User(
            username = form.username.data,
            password = form.password.data,
        )
        db.session.add(new_user)
        db.session.commit()
        flash('New User Created!')
        return redirect(url_for('main.homepage', user_id=new_user.id))
    return render_template('create_user.html', form=form)


##########################################
#           Post Routes                 #
##########################################

#create post
@main.route('/create_post', methods=['GET', 'POST'])
@login_required
def create_post():
    form = PostForm()
    #validate form
    if form.is_submitted():
        new_post = Post(
            title = form.title.data,
            caption = form.caption.data,
            photo_url = form.photo_url.data,
            created_by = flask_login.current_user
        )
        db.session.add(new_post)
        db.session.commit()
        flash('New Post Created!')
        return redirect(url_for('main.post_detail', post_id=new_post.id))
    return render_template('create_post.html', form=form)

# read and update post
@main.route('/post/<post_id>', methods=['GET', 'POST'])
@login_required
def post_detail(post_id):
    post = Post.query.get(post_id)
    form = PostForm(obj=post)

    if form.validate_on_submit():
        post.title = form.title.data
        post.caption = form.caption.data
        post.photo_url = form.photo_url
        db.session.commit()
        flash ('Post successfully editted.')
        return redirect(url_for('main.post_detail', post_id=post.id))
    return render_template('post_detail.html', post=post, form=form)

# delete post
@main.route('/delete_post/<post_id>', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get(post_id)
    if not post:
        abort(404)
    if request.method == 'POST':
        post = Post.query.get(post_id)
        db.session.delete(post)
        db.session.commit()
        flash('Post was deleted successfully', 'success')
        return redirect(url_for('main.homepage'))
    return render_template('post_detail.html', post=post)


##########################################
#           Comment Routes               #
##########################################

@main.route('/add_comment/<post_id>', methods=['POST'])
@login_required
def add_comment(post_id):
    post = Post.query.get(post_id)
    form = CommentForm(obj=post)
    if form.validate_on_submit():
        new_comment = CommentForm (
            comment = form.comment.data,
            created_by = flask_login.current_user
        )
        db.session.add(new_comment)
        post.all_comments.append(new_comment)
        db.session.commit()
        flash('Comment Added.')
        return redirect(url_for('post_detail.html', post_id=post.id))
    return render_template('create_comment.html', form=form)  

#delete comment
@main.route('/delete_comment/<comment_id>', methods=['GET', 'POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get(comment_id)
    if not comment:
        abort(404)
    if request.method == 'POST':
        comment = Comment.query.get(comment_id)
        db.session.delete(comment)
        db.session.commit()
        flash('Story was deleted successfully', 'success')
        return redirect(url_for('main.homepage'))
    return render_template('post_detail.html', comment=comment)

##########################################
#           Story Routes                 #
##########################################


#create story
@main.route('/create_story', methods=['GET', 'POST'])
@login_required
def create_story():
    form = StoryForm()
    if form.is_submitted():
        new_story = Story(
            photo_url = form.photo_url.data,
            created_by = flask_login.current_user
        )
        db.session.add(new_story)
        db.session.commit()
        flash('New Story Created!')
        return redirect(url_for('main.story_detail', story_id=new_story.id))
    return render_template('create_story.html', form=form)

# read and update story
@main.route('/story/<story_id>', methods=['GET', 'POST'])
@login_required
def story_detail(story_id):
    story = Story.query.get(story_id)
    form = StoryForm(obj=story)
    if form.validate_on_submit():
        story.photo_url = form.photo_url
        db.session.commit()
        flash ('Story successfully editted.')
        return redirect(url_for('main.story_detail', story_id=story.id))
    return render_template('story_detail.html', story=story, form=form)

# delete story
@main.route('/delete_story/<story_id>', methods=['GET', 'POST'])
@login_required
def delete_story(story_id):
    story = Story.query.get(story_id)
    if not story:
        abort(404)
    if request.method == 'POST':
        story = Story.query.get(story_id)
        db.session.delete(story)
        db.session.commit()
        flash('Story was deleted successfully', 'success')
        return redirect(url_for('main.homepage'))
    return render_template('post_detail.html', story=story)

only_pets/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Only Pets Socials</title>
        <!-- <link rel="stylesheet" href="/static/style.css"> -->
        <link rel="stylesheet" href="../static/base.css">
        <link rel="stylesheet" href="../static/posts.css">
        <link rel="stylesheet" href="../static/story.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            <nav>
                <a href="/">Home</a>
                <div>
                    {% if current_user.is_authenticated %}
                     <a href="/create_post">Add Post</a>
                     <a href="/create_story">Add Story</a>
                    <a href="/logout">Log Out</a>
                    <!-- <a href="/profile/{{ current_user }}">My profile</a> -->
                    {% else %}
                    <a href="/signup">Sign Up</a>
                    <a href="/login">Log In</a>
                    {% endif %}
                </div>
            </nav>

            {% if current_user.is_authenticated %}
            <p>You are logged in as {{ current_user.username }}</p>
            {% endif %}

            {% for message in get_flashed_messages() %}
                <p>{{ message }}</p>
            {% endfor %}

            {% block content %}{% endblock %}
        </div>
    </body>
</html>

only_pets/templates/create_comment.html
{% extends 'base.html' %}
{% block content %}

<h1>New Comment</h1>

<form method="POST" action="{{ url_for('main.add_comment', post_id=post.id) }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Type your comment below:</legend>
        
        {{ form.text.label }}
        {{ form.text(placeholder="Enter text here: ") }}
      
       {{ form.submit }}

    </fieldset>
</form>


{% endblock %}

only_pets/templates/create_post.html
{% extends 'base.html' %}
{% block content %}

<h1>New Post</h1>

<form method="POST" action="{{ url_for('main.create_post') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Please enter your information:</legend>
        
        {{ form.title.label }}
        {{ form.title(placeholder="Enter title here: ") }}

        {{ form.caption.label }}
        {{ form.caption(placeholder="Type your caption here: ") }}

        {{ form.photo_url.label }}
        {{ form.photo_url(placeholder="Enter photo url here:") }}
      
       {{ form.submit }}

    </fieldset>
</form>


{% endblock %}

only_pets/templates/create_story.html
{% extends 'base.html' %}
{% block content %}

<h1>New Story</h1>

<form method="POST" action="{{ url_for('main.create_story') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Please choose a photo to add to your story:</legend>

        {{ form.photo_url.label }}

        {{ form.photo_url(placeholder="Enter photo url here: ") }}
      
       {{ form.submit }}
    

    </fieldset>
</form>


{% endblock %}

only_pets/templates/create_user.html
{% extends 'base.html' %}
{% block content %}

<h1>New User</h1>

<form method="POST" action="{{ url_for('main.create_user') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Create a user</legend>
        
        {{ form.username.label }}
        {{ form.username(placeholder="Enter username here: ") }}

        {{ form.password.label }}
        {{ form.password(placeholder="************* ") }}
      
       {{ form.submit }}

    </fieldset>
</form>


{% endblock %}

only_pets/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h2>Stories</h2>
<!-- Display all the stories here -->
<section id="story-container">
    <section id="stories">
        {% for story in all_stories%}
        <div id="story">
            <a href="/story/{{ story.id }}"> <img id = "story-image" src="{{ story.photo_url }}" alt="{{ story.id }}" width="200px" /></a> 
        </div>
        {% endfor %}
    </section>
</section>


<h2>Posts</h2>
<!-- Display all the posts here -->
<section id="post-container">
    <section id="posts">
        {% for post in all_posts %}
        <div id="post">
            <a href="/post/{{ post.id }}"> <img src="{{ post.photo_url }}" alt="{{ post.caption }}" width="200px"></a> 
            <p><strong>{{ post.caption }}</strong></p>
            <img>
        </div>
        {% endfor %}
    </section>
</section>

<h2>Users</h2>

<p>
    <a href="/create_user">+ New User</a>
</p>

<ul>
    {% for user in all_users %}
        <li><a href="/profile/{{ user.username }}">{{ user.username }}</a></li>
    {% endfor %}
</ul>



{% endblock %}

only_pets/templates/login.html
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

only_pets/templates/post_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>{{post.title}}</h1>

<p><img src="{{ post.photo_url }}" width="250px" height="250px"></p>

<p>{{ post.caption }}</p>
<p><strong>Created by: </strong>{{ post.created_by.username }}</p>

<!-- TODO Add post-comments -->
<form method="POST" action="{{ url_for('main.delete_post', post_id=post.id) }}">
    {{ form.csrf_token }}
    <button type="submit">Delete Post</button> 
</form>

<!-- <form method="POST" action="{{ url_for('main.add_comment', post_id=post.id) }}">
    {{ form.csrf_token }}
    <button type="submit">Add a Comment</button> 
</form> -->

<h2>Edit Post</h2>

<form method="POST" action="{{ url_for('main.post_detail', post_id=post.id )}}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Please update your item</legend>
        {{ form.title.label }}
        {{ form.title(placeholder="YYYY-MM-DD") }}

        {{ form.caption.label }}
        {{ form.caption(placeholder="Type your caption here:") }}

        {{ form.photo_url.label }}
        {{ form.photo_url(placeholder="Enter photo url here:") }}
      
       {{ form.submit }}
    </fieldset>
   
</form>

{% endblock %}

only_pets/templates/profile.html
{% extends 'base.html' %}

{% block content %}

<p>
Welcome to {{ user.username }}'s profile.
</p>

<section id="post-container">
    <section id="posts">
        {% for post in posts %}
        <div id="post">
            <a href="/post/{{ post.id }}"> <img src="{{ post.photo_url }}" alt="{{ post.caption }}" width="200px"></a> 
            <p><strong>{{ post.caption }}</strong></p>
            <img>
        </div>
        {% endfor %}
    </section>
</section>

{% endblock %}

only_pets/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>

<form action="/signup" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}

    </fieldset>
</form>

{% endblock %}

only_pets/templates/story_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Your current story</h1>

<p><img src="{{ story.photo_url }}" width="250px" height="250px"></p>
<p><strong>Created by: </strong>{{ story.created_by.username }}</p>

<form method="POST" action="{{ url_for('main.delete_story', story_id=story.id) }}">
    {{ form.csrf_token }}
    <button type="submit">Delete Story</button> 
</form>


<h2>Edit Story</h2>

<form method="POST" action="{{ url_for('main.story_detail', story_id=story.id )}}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Please update your story</legend>
        {{ form.photo_url.label }}
        {{ form.photo_url(placeholder="Enter photo url here:") }}
       {{ form.submit }}
    </fieldset>
   
</form>

{% endblock %}